# Generated by Django 4.0.2 on 2022-02-11 19:40

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'permissions': [('premium_articles', 'Peut voir les articles premiums')]},
        ),
        migrations.AddField(
            model_name='articles',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(related_name='blogs_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='outils',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='articles',
            name='post_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.articles')),
            ],
        ),
    ]
