# Generated by Django 4.0.2 on 2022-02-13 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_options_articles_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['update_date'], 'permissions': [('premium_articles', 'Peut voir les articles premiums')]},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default='a new comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='csttrx', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
