# Generated by Django 4.0.2 on 2022-02-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='photo',
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
