# Generated by Django 4.0.2 on 2022-02-25 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articles_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page_visited', models.TextField()),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
