# Generated by Django 4.0.2 on 2022-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_articles_slug_alter_articles_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=250),
        ),
    ]
