# Generated by Django 4.0.2 on 2022-02-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=5000)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=5000)),
                ('Image', models.ImageField(blank=True, upload_to='', verbose_name='project image')),
                ('publish_at', models.DateField(blank=True, verbose_name='date of publish')),
                ('website', models.URLField(blank=True)),
                ('githup', models.URLField(blank=True)),
            ],
        ),
    ]
