# Generated by Django 4.0.2 on 2022-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('etablisement', models.CharField(max_length=500)),
                ('poste', models.CharField(blank=True, max_length=120, verbose_name='Niveau de formation')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Start date ')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('etab_website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='formation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Image',
        ),
        migrations.AddField(
            model_name='formation',
            name='Level',
            field=models.CharField(blank=True, max_length=120, verbose_name='Niveau de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='formation',
            name='etab_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='etablisement',
            field=models.CharField(default='University of Batna2', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Start date '),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='project image'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish_at',
            field=models.DateField(blank=True, null=True, verbose_name='date of publish'),
        ),
    ]
